[package]
name = "ctf"
version = "0.1.0"
authors = ["Alexandre Beaulieu <alex@segfault.me>"]
description = "Toolkit to help CTF teams synchronize during events."
license = "MIT"

[dependencies]
rusqlite = "0.13.0"
tempfile = "3"
chrono = "0.4"
